personal_data_blue : 'Data/blue/personal_data_blue.xlsx'
verbal_fluency_test_blue : 'Data/blue/verbal_fluency_test_blue.xlsx'
stroop_test_blue : 'Data/blue/stroop_test_blue.xlsx'
stop_signal_test_blue : 'Data/blue/stop_signal_test_blue.xlsx'
flanker_test_blue : 'Data/blue/flanker_test_blue.xlsx'
digit_span_test_blue : 'Data/blue/digit_span_test_blue.xlsx'

personal_data_green : 'Data/green/personal_data_green.xlsx'
verbal_fluency_test_green : 'Data/green/verbal_fluency_test_green.xlsx'
stroop_test_green : 'Data/green/stroop_test_green.xlsx'
stop_signal_test_green : 'Data/green/stop_signal_test_green.xlsx'
flanker_test_green : 'Data/green/flanker_test_green.xlsx'
digit_span_test_green : 'Data/green/digit_span_test_green.xlsx'

personal_data_red : 'Data/red/personal_data_red.xlsx'
verbal_fluency_test_red : 'Data/red/verbal_fluency_test_red.xlsx'
stroop_test_red : 'Data/red/stroop_test_red.xlsx'
stop_signal_test_red : 'Data/red/stop_signal_test_red.xlsx'
flanker_test_red : 'Data/red/flanker_test_red.xlsx'
digit_span_test_red : 'Data/red/digit_span_test_red.xlsx'

personal_data_pink : 'Data/pink/personal_data_pink.xlsx'
verbal_fluency_test_pink : 'Data/pink/verbal_fluency_test_pink.xlsx'
stroop_test_pink : 'Data/pink/stroop_test_pink.xlsx'
stop_signal_test_pink : 'Data/pink/stop_signal_test_pink.xlsx'
flanker_test_pink : 'Data/pink/flanker_test_pink.xlsx'
digit_span_test_pink : 'Data/pink/digit_span_test_pink.xlsx'

personal_data_orange : 'Data/orange/personal_data_orange.xlsx'
verbal_fluency_test_orange : 'Data/orange/verbal_fluency_test_orange.xlsx'
stroop_test_orange : 'Data/orange/stroop_test_orange.xlsx'
stop_signal_test_orange : 'Data/orange/stop_signal_test_orange.xlsx'
flanker_test_orange : 'Data/orange/flanker_test_orange.xlsx'
digit_span_test_orange : 'Data/orange/digit_span_test_orange.xlsx'