personal_data_blue : '/commons/dsls/hydrohomies/Data/blue/personal_data_blue.xlsx'
verbal_fluency_test_blue : '/commons/dsls/hydrohomies/Data/blue/verbal_fluency_test_blue.xlsx'
stroop_test_blue : '/commons/dsls/hydrohomies/Data/blue/stroop_test_blue.xlsx'
stop_signal_test_blue : '/commons/dsls/hydrohomies/Data/blue/stop_signal_test_blue.xlsx'
flanker_test_blue : '/commons/dsls/hydrohomies/Data/blue/flanker_test_blue.xlsx'
digit_span_test_blue : '/commons/dsls/hydrohomies/Data/blue/digit_span_test_blue.xlsx'

personal_data_green : '/commons/dsls/hydrohomies/Data/green/personal_data_green.xlsx'
verbal_fluency_test_green : '/commons/dsls/hydrohomies/Data/green/verbal_fluency_test_green.xlsx'
stroop_test_green : '/commons/dsls/hydrohomies/Data/green/stroop_test_green.xlsx'
stop_signal_test_green : '/commons/dsls/hydrohomies/Data/green/stop_signal_test_green.xlsx'
flanker_test_green : '/commons/dsls/hydrohomies/Data/green/flanker_test_green.xlsx'
digit_span_test_green : '/commons/dsls/hydrohomies/Data/green/digit_span_test_green.xlsx'

personal_data_red : '/commons/dsls/hydrohomies/Data/red/personal_data_red.xlsx'
verbal_fluency_test_red : '/commons/dsls/hydrohomies/Data/red/verbal_fluency_test_red.xlsx'
stroop_test_red : '/commons/dsls/hydrohomies/Data/red/stroop_test_red.xlsx'
stop_signal_test_red : '/commons/dsls/hydrohomies/Data/red/stop_signal_test_red.xlsx'
flanker_test_red : '/commons/dsls/hydrohomies/Data/red/flanker_test_red.xlsx'
digit_span_test_red : '/commons/dsls/hydrohomies/Data/red/digit_span_test_red.xlsx'

personal_data_purple : '/commons/dsls/hydrohomies/Data/purple/personal_data_purple.xlsx'
verbal_fluency_test_purple : '/commons/dsls/hydrohomies/Data/purple/verbal_fluency_test_purple.xlsx'
stroop_test_purple : '/commons/dsls/hydrohomies/Data/purple/stroop_test_purple.xlsx'
stop_signal_test_purple : '/commons/dsls/hydrohomies/Data/purple/stop_signal_test_purple.xlsx'
flanker_test_purple : '/commons/dsls/hydrohomies/Data/purple/flanker_test_purple.xlsx'
digit_span_test_purple : '/commons/dsls/hydrohomies/Data/purple/digit_span_test_purple.xlsx'

personal_data_pink : '/commons/dsls/hydrohomies/Data/pink/personal_data_pink.xlsx'
verbal_fluency_test_pink : '/commons/dsls/hydrohomies/Data/pink/verbal_fluency_test_pink.xlsx'
stroop_test_pink : '/commons/dsls/hydrohomies/Data/pink/stroop_test_pink.xlsx'
stop_signal_test_pink : '/commons/dsls/hydrohomies/Data/pink/stop_signal_test_pink.xlsx'
flanker_test_pink : '/commons/dsls/hydrohomies/Data/pink/flanker_test_pink.xlsx'
digit_span_test_pink : '/commons/dsls/hydrohomies/Data/pink/digit_span_test_pink.xlsx'

personal_data_orange : '/commons/dsls/hydrohomies/Data/orange/personal_data_orange.xlsx'
verbal_fluency_test_orange : '/commons/dsls/hydrohomies/Data/orange/verbal_fluency_test_orange.xlsx'
stroop_test_orange : '/commons/dsls/hydrohomies/Data/orange/stroop_test_orange.xlsx'
stop_signal_test_orange : '/commons/dsls/hydrohomies/Data/orange/stop_signal_test_orange.xlsx'
flanker_test_orange : '/commons/dsls/hydrohomies/Data/orange/flanker_test_orange.xlsx'
digit_span_test_orange : '/commons/dsls/hydrohomies/Data/orange/digit_span_test_orange.xlsx'